baseURL = "https://jobsdocs.ccwu.cc/"
title = "Jobs Docs"
theme = "hugo-book"
defaultContentLanguage = "zh-cn"

enableGitInfo = false 
disablePathToLower = false

disableKinds = ["taxonomy", "term"]

relativeURLs = true
canonifyURLs = false

[params]
BookTheme = "auto"
BookToC = true
BookSearch = true
BookComments = false
BookSection = "docs"
BookDateFormat = "2006-01-02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false